version: "3.3"
services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      #- "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      #- "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      #- "--entryPoints.websecure.forwardedHeaders.insecure=true"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,172.18.0.1/16,172.17.0.1/16"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,172.18.0.1/16,172.17.0.1/16"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=besmirzanaj@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  echoip:
    image: beszan/echoip:v1.5
    container_name: echoip
    restart: always
    hostname: "ifconfig.cloudalbania.com"
    command: ["-r", "-H", "X-Real-IP", "-a", "/usr/share/GeoIP/GeoLite2-ASN.mmdb", "-c", "/usr/share/GeoIP/GeoLite2-City.mmdb", "-f", "/usr/share/GeoIP/GeoLite2-Country.mmdb"]
    #command: ["-H", "X-Real-IP"]
    volumes:
      - "/usr/share/GeoIP/:/usr/share/GeoIP/"
    deploy:
      resources:
        limits:
          memory: 64M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.echoip-https.rule=Host(`ifconfig.cloudalbania.com`)"
      - "traefik.http.routers.echoip-https.entrypoints=websecure"
      - "traefik.http.routers.echoip-https.tls=true"
      - "traefik.http.routers.echoip-https.service=echoip-https"
      - "traefik.http.routers.echoip-https.tls.certresolver=myresolver"
      - "traefik.http.services.echoip-https.loadbalancer.server.port=8080"
      - "traefik.http.services.echoip-https.loadBalancer.passHostHeader=true"
      - "traefik.http.routers.echoip-http.rule=Host(`ifconfig.cloudalbania.com`)"
      - "traefik.http.routers.echoip-http.entrypoints=web"
      - "traefik.http.services.echoip-http.loadbalancer.server.port=8080"
      - "traefik.http.routers.echoip-http.service=echoip-http"
      - "traefik.http.services.echoip-http.loadBalancer.passHostHeader=true"
